apiVersion: v1
kind: Service
metadata:
  labels:
    app: connect-four
  name: connect-four
spec:
  ports:
  - port: 8080
    name: low
    protocol: TCP
    targetPort: 80
  selector:
    app: connect-four
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: connect-four
  name: connect-four
spec:
  replicas: 3
  selector:
    matchLabels:
      app: connect-four
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: connect-four
    spec:
      containers:
      - image: mfryman7337/connect-four
        name: connect-four
        ports:
        - containerPort: 80
        resources: {}
